Trying to fix download issue
- added .idea folder to gitignore file;
- added echoes for logging;
- added github user and branch to onlinesetup script;
- added removal magento archive in case mkdir or tar error as a separate function;

diff --git a/compose/bin/download b/compose/bin/download
--- a/compose/bin/download
+++ b/compose/bin/download
@@ -3,19 +3,40 @@
 
 edition=${2:-community}
 
+function extract_archive {
+    [ -z "$1" ] && echo "File for extraction is not provided" && exit
+    file=$1
+
+    [ ! -f "$file" ] && echo "File not found for extraction" && exit
+    destination=$2
+
+    [ ! -d "$destination" ] && mkdir -p "$destination"
+
+    tar xzf "$file" -o -C "$destination"
+
+    if [ "$?" == 0 ]; then return;
+
+    echo "Error during archive extraction. Try again"
+    rm -v ~/.docker-magento/magento2-$1.tar.gz
+    exit
+}
+
 if [[ "$edition" == "enterprise" ]]; then
     rm -rf src
+    echo "Creating enterprise project by composer"
     composer create-project --repository=https://repo.magento.com/ --ignore-platform-reqs magento/project-enterprise-edition=$1 src
     exit 0
 fi
 
 if [ ! -f ~/.docker-magento/magento2-$1.tar.gz ]; then
     mkdir -p ~/.docker-magento
+    echo "Downloading Magento Community from pubfiles.nexcess.net..."
     (cd ~/.docker-magento && curl -fOL http://pubfiles.nexcess.net/magento/ce-packages/magento2-$1.tar.gz)
 fi
 
 # Fallback download to hypernode if archive doesn't exist on Nexcess (smaller than 1MB)
 if [ $(find ~/.docker-magento/magento2-$1.tar.gz -size -1M) ]; then
+    echo "Failed to download, downloading Magento Community from www.magento.mirror.hypernode.com"
     (cd ~/.docker-magento && curl -o magento2-$1.tar.gz -fOL https://www.magento.mirror.hypernode.com/releases/magento-$1.tar.gz)
 fi
 
@@ -27,5 +48,5 @@ if [ ! -f ~/.docker-magento/magento2-$1.tar.gz ]; then
     composer create-project --repository=https://repo.magento.com/ --ignore-platform-reqs magento/project-community-edition=$1 src
 else
     echo "Extracting magento2-$1.tar.gz to ./src"
-    mkdir -p src && tar xzf ~/.docker-magento/magento2-$1.tar.gz -o -C src
+    extract_archive ~/.docker-magento/magento2-$1.tar.gz ./src
 fi
